---
abstract: 'Implicit random columns'
author:
  - 'Bernhard Graf <graf@cpan.org>'
build_requires:
  Path::Class: 0
  SQL::Translator: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-RandomColumns
no_index:
  directory:
    - inc
    - t
recommends:
  DBD::SQLite: 1.11
requires:
  DBIx::Class: 0.08009
version: 0.003000
